---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
    test-component: sink
data:
  redis-config: |-
    maxmemory 1gb
    maxmemory-policy allkeys-lru 
    dir /redis-master-data
    protected-mode no
    bind 0.0.0.0
    port 6379
    loadmodule /opt/redis-stack/lib/redistimeseries.so DUPLICATE_POLICY LAST
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
    test-component: sink
spec:
  selector:
    app: redis
    deployment: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      deployment: redis
  template:
    metadata:
      labels:
        app: redis
        deployment: redis
    spec:
      containers:
        - resources: {}
          name: redis
          image: redis/redis-stack-server:7.2.0-v10
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "1Gi"
#              cpu: "0.5"
          volumeMounts:
            - mountPath: /redis-master-data
              name: redis-master-volume
            - mountPath: /redis-master
              name: config
      volumes:
        - name: redis-master-volume
          emptyDir: {}
        - name: config
          configMap:
            name: redis-config
            items:
              - key: redis-config
                path: redis.conf
  strategy:
    type: Recreate
